### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by weeebdev** [rjoonas/heroku-docker-nginx-example#7]
That's what happens when try to deploy

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/48881444/176511031-66b7aed6-b6ec-48ef-accf-ff75ed249a80.png">

**Comment by rjoonas** [comment]
Hi, that means that your image is built with an architecture not supported by Heroku. Happens if you're using e.g. a new Mac with Apple Silicon.

One way to fix it is to use [docker buildx](https://docs.docker.com/buildx/working-with-buildx/) to build for `linux/amd64` instead of your system architecture. Assuming a Heroku app with the name of `nginx-example`:

```
docker buildx build --platform linux/amd64 -t nginx-example .
docker tag nginx-example registry.heroku.com/nginx-example/web
docker push registry.heroku.com/nginx-example/web
heroku container:release web -a nginx-example
```

**Comment by rjoonas** [comment]
Heroku also builds the image for you on `git push` so you should be able to use that after the initial deploy.
